version: '3'

services:
  mysql.agenda-petshop:
    image: mysql
    ports:
      - "3308:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: agendamento-petshop
      MYSQL_USER: dancesar
      MYSQL_PASSWORD: 05041979
    volumes:
      - mysql.agendamento-petshop:/var/lib/mysql

      docker container run --rm -d -p 3308:3306 --name thor.mysql -e MYSQL_ROOT_PASSWORD=homer -e MYSQL_DATABASE=agendamento-petshop -e MYSQL_USER=dancesar -e MYSQL_PASSWORD=05041979 -v thor.mysql:/var/lib/mysql mysql:5.7

      docker container exec -it thor.mysql mysql -udancesar -p agendamento-petshop